name: Jobs Execution test

on:
  push:
    branches:
      - main



jobs:
  concurrency-job1:
    name: concurrency job1
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - name: Hi
        run: | 
          sleep 10
          echo Hi 1

  concurrency-job2:
    name: concurrency job2
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - name: Hiii
        run: |
          sleep 10
          echo Hi 2


  deploy-job:
    name: Deploy it
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Test build output
        run: |
          echo ${{ needs.build_job.outputs.build-output}}
        
        

  build_job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOutput}}
    name: Build it
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Define output variable
        id: buildStep
        run: |
          env=$(node --version)
          echo "buildOutput=$env" >> "$GITHUB_OUTPUT"
      - name: Print the output
        run: echo "The output is ${{ steps.buildStep.outputs.buildOutput }}"