name: Jobs Execution test

on:
  push:
    branches:
      - main



jobs:
  deploy-job:
    name: Deploy it
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Test build output
        run: |
          echo ${{ needs.build_job.outputs.build-output}}
        
        

  build_job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOutput}}
    name: Build it
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Define output variable
        id: buildStep
        run: |
          env=$(node --version)
          echo "buildOutput=$env" >> "$GITHUB_OUTPUT"
          echo ${{ $GITHUB_OUTPUT }}