name: Simple workflow test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  self_hosted_job:
    name: the self hosted job runner
    runs-on: self-hosted
    steps:
    - name: step in self hosted runner
      run: echo "hello this is my self hosted runner"
  job_1:
    name: the first job
    runs-on: ubuntu-latest
    steps:
      - name: my first step
        run: echo "Hello workflow"
      - name: my second step
        run: echo "The workflow is running"