name: Workflow to test diff variables

on:
  push:
    branches:
      - main

jobs:
  job_1:
    env:
     aBoolean: ${{ true }}
     aNull: ${{ null }}
     aNumber: ${{ 42 }}
     aString: hello world
    name: job to test expressions
    runs-on: macos-latest
    steps:
      - name: for boolean
        if: ${{ fromJSON(env.aBoolean) }}
        run: |
          echo this shall run
          echo ${{ fromJSON(env.aBoolean) }}

      - name: for null
        if: ${{ env.aNull == null }}
        run: echo this is a null func.

      - name: for string pass
        if: ${{ contains( env.aString , 'hello' ) }}
        run: echo this should not fail
      - name: if above pass
        if: ${{ success() && always() }}
        env:
          format_var_success: ${{ format('Github {0} {1}', 'is', 'awesome!') }}
        run: | 
          echo the for string step is passed!
          echo ${{ env.format_var_success }}

      - name: for string fails
        if: ${{ contains( env.aString , 'hellos' ) }}
        run: echos "this should fail"
      - name: if above fails
        if: ${{ failure() }}
        env:
          format_var_fail: ${{ format('Github {0} {1}', 'is', 'stupid!') }}
        run: |
          echo the for string step is passed!
          echo ${{ env.format_var_fail }}
          
          

  job_2:
    env:
      Job_Level_Custom_Variable: "4"
    name: job to run variable
    runs-on: macos-latest
    steps:
      - env:
          Step_Level_Custom_Variable: "6"
        name: step to run custom variable
        run: |
          echo $Workflow_Level_Custom_Variable
          echo ${{env.Job_Level_Custom_Variable}}
          echo ${{env.Step_Level_Custom_Variable}}

      - name: step to run default variable
        run: |
          echo ${{ github.actor }}

      - name: step to run secret
        run: |
          echo ${{ secrets.SECRET }}

      - name: step to run configuration variable
        run: |
         echo ${{ vars.CONF_VARIABLE }}
